### ISSUE TITLE
add option to view multiple overlays with different colors

### ISSUE THREAD

**Issue by ahmedhosny** [gigmade/cellexpress-proto#1]

**Comment by bebbi** [comment]
either static (e.g. 2 color versions hard-coded on S3),
or a library that on-the-fly converts given color (e.g. same for all overlays) to any color of choice

**Comment by ahmedhosny** [comment]
#18 fixes this. draws overlays on canvas and changes color through color selector
Only 2 overlays currently supported
Future improvement: allow (+) and (-) buttons for adjusting number of overlays to draw.
