### ISSUE TITLE
add well annotation - which well is what? (group wells)

### ISSUE THREAD

**Issue by ahmedhosny** [gigmade/cellexpress-proto#3]

**Comment by bebbi** [comment]
Similar to a tagging mechanism? 1 well : n annotations.

**Comment by ahmedhosny** [comment]
done to a good extent:
good to haves:
_marquee selection for multiple cells - not you just need to click on all.
_highlight all when one annotaed cell is selected

**Comment by bebbi** [comment]
this includes seeing colors AND annotations

**Comment by ahmedhosny** [comment]
now has toggle to switch between "annotation" mode and "endpoint" mode
