### ISSUE TITLE
clean up results button?

### ISSUE THREAD

**Issue by bebbi** [gigmade/cellexpress-proto#33]
Clicking results from

http://cellexpress.herokuapp.com/result?link=https://s3.amazonaws.com/cellexpress/i.ahmedhosny@gmail.com/myFirstJob/results

results in a page saying

oops! I can't find the results.csv file :(

**Comment by ahmedhosny** [comment]
works perfectly fine for me, click again.

**Comment by bebbi** [comment]
unchanged behaviour. Did try in FF and Chrome, both same result.

**Comment by bebbi** [comment]
and safari

**Comment by ahmedhosny** [comment]
cleaned up
