### ISSUE TITLE
possibly, replace rewind arrow with back/up arrow?

### ISSUE THREAD

**Issue by bebbi** [gigmade/cellexpress-proto#42]
https://www.google.com/search?q=backup+symbol&client=firefox-b-ab&biw=1309&bih=705&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi-uaT16tXRAhXkKMAKHbAaCdAQ_AUIBigB#tbm=isch&q=return+back+up+symbol&imgrc=4_8fjbHaU7gfEM%3A

**Comment by ahmedhosny** [comment]
doone
