### ISSUE TITLE
add ability to exclude outliers

### ISSUE THREAD

**Issue by ahmedhosny** [gigmade/cellexpress-proto#6]

**Comment by bebbi** [comment]
Related, plot constrained to subsets of wells. (subsets defined by well "tags")

**Comment by ahmedhosny** [comment]
how do you think this can be done in terms of UI?
double click on wells opens the images - we can use one click to exclude but its not ideal in terms of UI - too confusing..

**Comment by ahmedhosny** [comment]
now excluding by group (no visual cue yet, but plot is updated), do you think this is useful? it just excluded one bar at a time.. i think excluding by single cell is more useful..

**Comment by ahmedhosny** [comment]
now excluding single cells - needs better UI than checkoxes
